### PR TITLE
Refactoring of iKartRosBridge

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
Move bridgeModule in own header file
Properly close all ports and free pointers
Use ros::ok() to detect whether module should be closed, so module closes gracefully
Auto-indent ikart_v1.sdf file

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
Hi @randaz81 @pattacini,
Would be great if you check and merge.

Thanks, Tobi

**Comment by randaz81** [comment]
iKartRosBridge is deprecated... I'm going to remove it from the repo...

**Comment by randaz81** [comment]
the same applies to iKartCtrl, iKartGoto ecc. All those modules are going to be removed. The new version is stored in the navigation repo. Additionally, you don't need anymore a bridge, all these module are able to communicate with ros without linking ros. ..

**Comment by Tobias-Fischer** [comment]
Ahhh okay cool, I see. Would you be so kind and give me a short introduction on how to use the iKart and ROS with the new modules? Basically, I just want to move the iKart around using the ROS navigation stack.

**Comment by Tobias-Fischer** [comment]
And maybe we should still merge this, some people might still be using the old version, and would be happy about the bugfix :)

**Pull request closed without merging**
